# Generated by Django 4.2.16 on 2025-10-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("add_staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("in_time", models.TimeField(blank=True, null=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Half Day", "Half Day"),
                            ("WFH", "WFH"),
                        ],
                        default="Present",
                        max_length=20,
                    ),
                ),
                ("branch", models.CharField(max_length=100)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="add_staff.staff",
                    ),
                ),
            ],
            options={
                "unique_together": {("staff", "date")},
            },
        ),
    ]
