# Generated by Django 5.1.7 on 2026-04-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_batch', '0001_initial'),
        ('add_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.AddField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(related_name='student_batches', to='add_batch.batch'),
        ),
    ]
