# Generated by Django 5.2.4 on 2025-10-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_franchise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfranchise',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
